FROM --platform=${BUILDPLATFORM} golang:1.20.1-alpine3.17 AS build
WORKDIR /src
ENV CGO_ENABLED=0
COPY . .
ARG TARGETOS
ARG TARGETARCH
RUN GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build

FROM scratch AS bin
COPY --from=build /src/elastictl /