name: Dispatcher Using Action
on:
  push:
    branches: [main]
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      organization:
        description: 'Kestrel repo organization'
        required: true
        default: 'opencybersecurityalliance'
      branch:
        description: 'Kestrel repo branch'
        required: true
        default: 'develop'
    
jobs:
  dispatch:
    name: Dispatch Using Action
    strategy:
      matrix:
        repo: [cmadam/hunting-stack-testing]
    runs-on: ubuntu-latest
    steps:
      - name: Print parameters
        run: |
          echo "organization: ${{ github.event.inputs.organization }}, branch: "${{ github.event.inputs.branch }}"
      - name: Dispatch to workflows
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: cmadam
          repo: hunting-stack-testing
          github_token: ${{ secrets.REMOTE_FINE_GRAINED_ACTIONS_TOKEN }}
          workflow_file_name: testing_receiver.yml
          ref: main
          wait_interval: 10
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true
          client_payload: '{"organization": "${{ github.event.inputs.organization }}", "branch": "${{ github.event.inputs.branch }}"}'