name: Dispatcher
on:
  push:
    branches: [main]
jobs:
  dispatch:
    name: Dispatch
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: [cmadam/hunting-stack-testing]
    timeout-minutes: 5
    steps:
      - name: Dispatch to workflows
        run: |
          curl -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.REMOTE_ACTIONS_TOKEN }}" \
          --request POST \
          --data '{"event_type": "testing_event"}' \
          https://api.github.com/repos/${{ matrix.repo }}/dispatches
