name: Integration Testing for Kestrel and STIX-Shifter Using GitHub Actions
on: 
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  integrated-testing:
    runs-on: ubuntu-20.04
    steps:
      - name: Worflow Information
        run: |
          echo "Triggered by ${{ github.actor }} through a ${{ github.event_name }} event."
          echo "Running on a ${{ runner.os }} server hosted by GitHub"
          echo "Running in ${{ github.repository }} repository, ${{ github.ref }} branch."
      - name: Launch the elastic docker image
        run: |
          docker network create elastic
          docker run -d --name elasticsearch --net elastic -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" elasticsearch:7.17.8
          sleep 5
          docker ps -a
      - name: Code Checkout
        uses: actions/checkout@v3
      - name: Kestrel Code Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.actor }}/kestrel-lang
          path: './kestrel-lang'
      - name: STIX-Shifter Code Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.actor }}/stix-shifter
          path: './stix-shifter'
      - name: elastictl Code Checkout
        uses: actions/checkout@v3
        with:
          repository: subbyte/elastictl
          path: './elastictl'
      - name: Virtual Environment Creation and Activation
        run: |
          pwd
          pip install --upgrade pip
          python3 -m venv huntingspace
          . huntingspace/bin/activate
          echo "VIRTUAL ENV:" $VIRTUAL_ENV
          echo "venv_activate=$VIRTUAL_ENV/bin/activate" >> $GITHUB_ENV
      - name: Install kestrel and STIX-Shifter from Source Code
        run: |
          source ${{ env.venv_activate }}
          cd ${{ github.workspace }} 
          cd stix-shifter
          VERSION=9.9.99 python3 setup.py install
          cd ../kestrel-lang
          sed -i 's/.*stix-shifter-utils.*/    stix-shifter-utils==9.9.99/' setup.cfg
          sed -i 's/.*stix-shifter=.*/    stix-shifter==9.9.99/' setup.cfg
          sed -i 's/.*stix-shifter>.*/    stix-shifter==9.9.99/' setup.cfg
          pip install .
      - name: Install elastictl
        run: |
          cp Dockerfile.build elastictl
          cd elastictl
          export DOCKER_BUILDKIT=1
          docker build --target bin --output bin/ -f Dockerfile.build .
          cp bin/elastictl ${{ github.workspace }}
          cd ${{ github.workspace }}
          ./elastictl e --help
      - name: Import test data in elastic instance
        run: |
          python import_data.py
          ./elastictl i -N test-ecs < test-ecs.data
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Job Status
        run: echo "This job's status is ${{ job.status }}."