name: Integration Testing Launcher
on:
  workflow_dispatch:
    inputs:
      organization:
        description: 'Kestrel repo organization'
        required: true
        default: 'opencybersecurityalliance'
      repository:
        description: 'Kestrel repo name'
        required: true
        default: 'kestrel-lang'
      branch:
        description: 'Kestrel repo branch'
        required: true
        default: 'develop'

jobs:
  receiver:
    runs-on: ubuntu-latest
    steps:
      - name: Testing event received
        run: |
          echo "GITHUB EVENT: ${{ toJson(github.event) }}"
          echo "Received the testing event, organization = ${{ github.event.inputs.organization }}, repository = ${{ github.event.inputs.repository }}, branch = ${{ github.event.inputs.branch }}"
          exit 0
